name: matt delhey
url: http://mattdelhey.com
description: man is spirit. but what is spirit?

permalink: /:year/:month/:day/:title/
paginate: 20
pygments: true

provider: google
tracking_id: 'UA-36824837-1'

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']